# permissions for end users to view appscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-sdk-operator1
    app.kubernetes.io/managed-by: kustomize
  name: appscaler-viewer-role
rules:
- apiGroups:
  - api.operator.wissam.com
  resources:
  - appscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.operator.wissam.com
  resources:
  - appscalers/status
  verbs:
  - get
